# /etc/docker/compose/pg/docker-compose.yml

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /home/marko/.pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL= #email, useful for 2FA
      - PGADMIN_DEFAULT_PASSWORD= #define pwd
    ports:
      - "5050:80"
    volumes:
      - /home/marko/.pgadmin-data:/var/lib/pgadmin
